export const CHIP8_MEMORY_SIZE = 0x1000;
export const CHIP8_PROGRAM_MEMORY_LOCATION = 0x200;
export const CHIP8_REGISTERS_COUNT = 0x10;
export const CHIP8_STACK_SIZE = 0x10;
export const CHIP8_DISPLAY_WIDTH = 64;
export const CHIP8_DISPLAY_HEIGHT = 32;